### ISSUE TITLE
Importing an identity from PC to MAC

### ISSUE THREAD

**Issue by somanyquestions** [AkashaProject/Translations#12]
Hi AKASHA team,

Here's what I want to achieve. I have a profile on AKASHA from the alpha days, which is simply "hilary". I'd like to keep that profile name when I use AKASHA via MetaMask, because, hey, it's pretty cool. Since the alpha I've become a MAC user. Is there any **easy** way to get my profile name back with my associated key?

I can see the alpha profile/UTC on my PC in keystore:

Local Disk (C:) > Users > OWner > AppData > Roaming > Ethereum > akasha-alpha > keystore

UTC--date-number--key/address

I have been able to upload the UTC file onto a cloud drive, but once I access the file from my MAC, the MAC doesn't recognize the file format and I don't where to go from here.

My computer science background is ZERO (in case that wasn't painfully evident already!).

Thanks for your help 😃 
Hilary

**Comment by sebastianrs95** [comment]
Hello!
Thank you for reaching us.
We have a guide for that here: https://akasha.helpscoutdocs.com/article/16-how-to-migrate-accounts

Regarding these kind of questions, please address them in the Discord Channel.

The issues posted here in Github are for technical problems regarding the dapp, both web and desktop.

So what you need to do is simply take that UTC file and paste it in the direction specified in the aforementioned guide. If you have more problems, please join us over at: https://discordapp.com/invite/JqqKasJ
