### ISSUE TITLE
Mention IPFS as part of the installation instructions

### ISSUE THREAD

**Issue by ShalokShalom** [AkashaProject/Translations#13]
If IPFS is important for Akasha to run, it could be named somewhere in the installation instructions. 

![screenshot_20180512_150709](https://user-images.githubusercontent.com/6344099/39957634-6956bf18-55f6-11e8-85dd-0545e35fa817.png)

**Comment by sebastianrs95** [comment]
hello, Shalok!
The greeting page mentions getting both Metamask and, albeit optional, IPFS Companion.
Also, in the blog post by Mihai, ['Mending the Gap'](https://blog.akasha.world/2018/04/18/akasha-web-mend-the-gap/), installing IPFS is also recommended. 
In the [Getting Started guide](https://akasha.helpscoutdocs.com/article/30-metamask-integration) we show the steps for integrating both Metamask and IPFS.

Do you think that there should be a message emphasizing the installation of IPFS Companion right after you log in?

Thank you for your feedback 😄

**Comment by ShalokShalom** [comment]
No, I mean IPFS itself. I figured out that I missed switching Companion into the embedded mode, you can mention that on the greeting page. 

IPFS Companion is critical, I think the term "recommended" is misplaced here, it is so important as MetaMask is.
