### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ChaceHunter** [AkashaProject/Translations#4]
- [x] Upload .json to GitHub

- [ ] Contact those already willing to help with translations, and link them to GitHub

- [ ] Reddit post asking for help in translating ALL the languages

**Comment by oneyesoneno** [comment]
I am ready to work on Indonesia Language.

**Comment by joelsteem** [comment]
Hello, project owner !!
Introduction, I am an interpreter from the Indonesian language, and I would like to join the AkashaProject/Community translation project.
Can I get permission to be an interpreter on your project?

**Comment by sebastianrs95** [comment]
Hello!
Thank you for your interest in collaborating with the translations. Here is the site that we are using for it:
https://crowdin.com/project/akasha

Please join our [Discord channel](https://discordapp.com/invite/JqqKasJ) to communicate with other translators!

Glad to have you on board 👍

**Comment by 42piratas** [comment]
@ChaceHunter Closing as it seems old/done
